// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6okjwnk-Ly4iCBA77EuHjB-UL4Wiagk',
    appId: '1:1000878401201:web:4a3c198d44b07ec547a490',
    messagingSenderId: '1000878401201',
    projectId: 'sajjadtech-f79b7',
    authDomain: 'sajjadtech-f79b7.firebaseapp.com',
    storageBucket: 'sajjadtech-f79b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdFr7eLFon5jMRHYEJpO6luTDm5Y6C_Rg',
    appId: '1:1000878401201:android:98911fca0ceb748f47a490',
    messagingSenderId: '1000878401201',
    projectId: 'sajjadtech-f79b7',
    storageBucket: 'sajjadtech-f79b7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm6okjwnk-Ly4iCBA77EuHjB-UL4Wiagk',
    appId: '1:1000878401201:web:93e404d0c90d2d1f47a490',
    messagingSenderId: '1000878401201',
    projectId: 'sajjadtech-f79b7',
    authDomain: 'sajjadtech-f79b7.firebaseapp.com',
    storageBucket: 'sajjadtech-f79b7.firebasestorage.app',
  );
}
